dist: bionic
language: python

branches:
  except:
    - gh-pages

python:
  - '3.8'

install:
  - pipenv install --dev --pre --skip-lock --sequential

script:
  - pytest --block-network

notifications:
  email: false

