dist: bionic
language: python

branches:
  except:
    - gh-pages

python:
  - '3.7.2'
  #- '3.8'


install:
  - pipenv install --dev --pre --skip-lock --sequential

script:
  - python -m aiokraken.model.tests
  - python -m aiokraken.utils.tests
  - python -m aiokraken.rest.schemas.tests
  - python -m aiokraken.tests
  - pytest -s tests --block-network

notifications:
  email: false

