dist: bionic
language: python

branches:
  except:
    - gh-pages

python:
  - '3.8.1'
  - '3.8.2'
  - '3.8.3'
  - '3.8.4'

install:
  - pipenv install --dev --pre --skip-lock --sequential

script:
  - pytest --block-network

notifications:
  email: false

