dist: bionic
language: python

branches:
  except:
    - gh-pages

python:
  - '3.8'


install:
  - pipenv install --dev --pre --skip-lock --sequential

script:
  - pytest aiokraken/utils/tests
  - pytest aiokraken/rest/schemas/tests
  - pytest aiokraken/rest/tests
  - pytest aiokraken/websockets/schemas/tests
  - pytest aiokraken/websockets/tests
  - pytest aiokraken/model/tests
  - pytest aiokraken/tests
  - pytest tests --block-network

notifications:
  email: false

