version: ~> 1.0
dist: bionic
language: python

branches:
  except:
    - gh-pages

python:
  # because that's my (and currently the only) development version
  - '3.8.2'
#  - '3.8.3'
#  - '3.8.4'
#  - '3.8.5'

install:
  - pipenv install --dev --pre --skip-lock --sequential

script:
  - pytest --import-mode=importlib --block-network

notifications:
  email: false

